-- Datenbank erstellen
CREATE DATABASE hoteldb;

-- Tabelle entfernen, falls sie existiert
DROP TABLE IF EXISTS hotelgaeste;

-- Tabelle erstellen
CREATE TABLE IF NOT EXISTS hotelgaeste
(
    id                             TEXT,
    Erwachsene                     INT,
    Kinder                         INT,
    Nächte_am_Wochenende           INT,
    Nächte_unter_der_Woche         INT,
    Verpflegungsplan               TEXT,
    Parkplatz                      INT,
    Zimmertyp                      TEXT,
    lead_time                      INT,
    Ankunftsjahr                   INT,
    Ankunftsmonat                  INT,
    Ankunftstag                    INT,
    Marktsegment                   TEXT,
    Wiederkehrender_Gast           INT,
    Vorherige_Stornierungen        INT,
    Vorherige_nicht_Stornierungen  INT,
    Durchschnittlicher_Zimmerpreis FLOAT,
    no_of_special_requests         INT,
    Buchungsstatus                 TEXT
);

-- Vorhandene csv importieren
COPY hotelgaeste
    FROM 'C:\Users\Admin\Documents\sql-project-04\Hotel_Reservations.csv'
    DELIMITER ','
    CSV HEADER;


SELECT *
FROM hotelgaeste;

-- unnötige Spalten löschen
ALTER TABLE hotelgaeste
    DROP COLUMN lead_time;

ALTER TABLE hotelgaeste
    DROP COLUMN no_of_special_requests;

ALTER TABLE hotelgaeste
    DROP COLUMN id;

SELECT *
FROM hotelgaeste;


-- ID Spalte hinzufügen

ALTER TABLE hotelgaeste
    ADD COLUMN id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;


-- mock_names erstellen

DROP TABLE IF EXISTS mock_names;

CREATE TABLE mock_names
(
    first_name TEXT,
    last_name  TEXT
);

COPY mock_names
    FROM 'C:\Users\Admin\Documents\sql-project-04\src\config\init\Kunden.csv'
    DELIMITER ','
    HEADER CSV;



-- ID Spalte hinzufügen

ALTER TABLE mock_names
    ADD COLUMN id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;


-- Joinen

SELECT *
FROM mock_names
JOIN hotelgaeste
USING (id);

SELECT * FROM hotelgaeste;



